// Basing this off REVM's bins/revme/src/cmd/statetest/runner.rs

use block_stm_revm::{BlockSTM, Storage};
use rayon::iter::{IntoParallelRefIterator, ParallelIterator};
use revm::db::PlainAccount;
use revm::primitives::{
    calc_excess_blob_gas, Account, AccountInfo, Address, BlobExcessGasAndPrice, BlockEnv, Bytecode,
    EVMError, InvalidTransaction, ResultAndState, TransactTo, TxEnv, U256,
};
use revme::cmd::statetest::models::{
    Env, SpecName, TestSuite, TestUnit, TransactionParts, TxPartIndices,
};
use revme::cmd::statetest::{
    merkle_trie::{log_rlp_hash, state_merkle_trie_root},
    utils::recover_address,
};
use std::path::Path;
use std::{collections::HashMap, fs, num::NonZeroUsize};
use walkdir::{DirEntry, WalkDir};

fn build_block_env(env: &Env) -> BlockEnv {
    BlockEnv {
        number: env.current_number,
        coinbase: env.current_coinbase,
        timestamp: env.current_timestamp,
        gas_limit: env.current_gas_limit,
        basefee: env.current_base_fee.unwrap_or_default(),
        difficulty: env.current_difficulty,
        prevrandao: env.current_random,
        blob_excess_gas_and_price: if let Some(current_excess_blob_gas) =
            env.current_excess_blob_gas
        {
            Some(BlobExcessGasAndPrice::new(current_excess_blob_gas.to()))
        } else if let (Some(parent_blob_gas_used), Some(parent_excess_blob_gas)) =
            (env.parent_blob_gas_used, env.parent_excess_blob_gas)
        {
            Some(BlobExcessGasAndPrice::new(calc_excess_blob_gas(
                parent_blob_gas_used.to(),
                parent_excess_blob_gas.to(),
            )))
        } else {
            None
        },
    }
}

fn build_tx_env(tx: &TransactionParts, indexes: &TxPartIndices) -> TxEnv {
    TxEnv {
        caller: if let Some(address) = tx.sender {
            address
        } else if let Some(address) = recover_address(tx.secret_key.as_slice()) {
            address
        } else {
            panic!("Failed to parse caller") // TODO: Report test name
        },
        gas_limit: tx.gas_limit[indexes.gas].saturating_to(),
        gas_price: tx.gas_price.or(tx.max_fee_per_gas).unwrap_or_default(),
        transact_to: match tx.to {
            Some(address) => TransactTo::Call(address),
            None => TransactTo::Create,
        },
        value: tx.value[indexes.value],
        data: tx.data[indexes.data].clone(),
        nonce: Some(tx.nonce.saturating_to()),
        chain_id: Some(1), // Ethereum mainnet
        access_list: tx
            .access_lists
            .get(indexes.data)
            .and_then(Option::as_deref)
            .unwrap_or_default()
            .iter()
            .map(|item| {
                (
                    item.address,
                    item.storage_keys
                        .iter()
                        .map(|key| U256::from_be_bytes(key.0))
                        .collect::<Vec<_>>(),
                )
            })
            .collect(),
        gas_priority_fee: tx.max_priority_fee_per_gas,
        blob_hashes: tx.blob_versioned_hashes.clone(),
        max_fee_per_blob_gas: tx.max_fee_per_blob_gas,
        eof_initcodes: Vec::new(),
        eof_initcodes_hashed: HashMap::new(),
    }
}

fn run_test_unit(unit: TestUnit) {
    for (spec_name, tests) in unit.post {
        // Should REVM know and handle these better, or it is
        // truly fine to just skip them?
        if matches!(
            spec_name,
            SpecName::ByzantiumToConstantinopleAt5 | SpecName::Constantinople | SpecName::Unknown
        ) {
            continue;
        }
        let spec_id = spec_name.to_spec_id();

        for test in tests {
            let mut chain_state: HashMap<Address, PlainAccount> = HashMap::new();
            let mut block_stm_storage = Storage::default();

            // Shouldn't we parse accounts as `Account` instead of `AccountInfo`
            // to have initial storage states?
            for (address, raw_info) in unit.pre.iter() {
                let code = Bytecode::new_raw(raw_info.code.clone());
                let info =
                    AccountInfo::new(raw_info.balance, raw_info.nonce, code.hash_slow(), code);
                chain_state.insert(*address, info.clone().into());
                block_stm_storage.insert_account(*address, Account::from(info));
            }

            match (
                test.expect_exception,
                BlockSTM::run(
                    block_stm_storage,
                    spec_id,
                    build_block_env(&unit.env),
                    vec![build_tx_env(&unit.transaction, &test.indexes)],
                    NonZeroUsize::MIN,
                ),
            ) {
                // Tests that expect execution to fail -> match error
                (Some(exception), Err(error)) => {
                    // TODO: Ideally the REVM errors would match the descriptive expectations more.
                    if exception != "TR_TypeNotSupported" && !matches!(
                        (exception.as_str(), &error),
                        (
                            "TR_BLOBLIST_OVERSIZE",
                            EVMError::Transaction(InvalidTransaction::TooManyBlobs{..})
                        ) | (
                            "TR_BLOBCREATE",
                            EVMError::Transaction(InvalidTransaction::BlobCreateTransaction)
                        ) | (
                            "TR_EMPTYBLOB",
                            EVMError::Transaction(InvalidTransaction::EmptyBlobs)
                        ) | (
                            "TR_BLOBVERSION_INVALID",
                            EVMError::Transaction(InvalidTransaction::BlobVersionNotSupported)
                        ) | (
                            "TransactionException.TYPE_3_TX_PRE_FORK|TransactionException.TYPE_3_TX_ZERO_BLOBS",
                            EVMError::Transaction(InvalidTransaction::MaxFeePerBlobGasNotSupported)
                        ) | (
                            "TransactionException.TYPE_3_TX_PRE_FORK",
                            EVMError::Transaction(InvalidTransaction::BlobVersionedHashesNotSupported)
                        ) | (
                            "TransactionException.INSUFFICIENT_ACCOUNT_FUNDS",
                            EVMError::Transaction(InvalidTransaction::LackOfFundForMaxFee{..})
                        ) | (
                            "TransactionException.TYPE_3_TX_INVALID_BLOB_VERSIONED_HASH",
                            EVMError::Transaction(InvalidTransaction::BlobVersionNotSupported)
                        ) | (
                            "TransactionException.INSUFFICIENT_MAX_FEE_PER_GAS",
                            EVMError::Transaction(InvalidTransaction::GasPriceLessThanBasefee)
                        ) | (
                            "TransactionException.TYPE_3_TX_ZERO_BLOBS",
                            EVMError::Transaction(InvalidTransaction::EmptyBlobs)
                        ) | (
                            "TransactionException.TYPE_3_TX_BLOB_COUNT_EXCEEDED",
                            EVMError::Transaction(InvalidTransaction::TooManyBlobs{..})
                        ) | (
                            "TransactionException.INSUFFICIENT_MAX_FEE_PER_BLOB_GAS",
                            EVMError::Transaction(InvalidTransaction::BlobGasPriceGreaterThanMax)
                        ) | (
                            "TransactionException.INITCODE_SIZE_EXCEEDED",
                            EVMError::Transaction(InvalidTransaction::CreateInitCodeSizeLimit)
                        ) | (
                            "TransactionException.INTRINSIC_GAS_TOO_LOW",
                            EVMError::Transaction(InvalidTransaction::CallGasCostMoreThanGasLimit)
                        ) | (
                            "TR_InitCodeLimitExceeded",
                            EVMError::Transaction(InvalidTransaction::CreateInitCodeSizeLimit)
                        ) | (
                            "TR_IntrinsicGas",
                            EVMError::Transaction(InvalidTransaction::CallGasCostMoreThanGasLimit)
                        ) | (
                            "TR_FeeCapLessThanBlocks",
                            EVMError::Transaction(InvalidTransaction::GasPriceLessThanBasefee)
                        ) | (
                            "TR_NoFunds",
                            EVMError::Transaction(InvalidTransaction::LackOfFundForMaxFee{..})
                        ) | (
                            "TR_TipGtFeeCap",
                            EVMError::Transaction(InvalidTransaction::PriorityFeeGreaterThanMaxFee)
                        ) | (
                            "SenderNotEOA",
                            EVMError::Transaction(InvalidTransaction::RejectCallerWithCode)
                        ) | (
                            "TR_NoFundsX",
                            EVMError::Transaction(InvalidTransaction::OverflowPaymentInTransaction)
                        ) | (
                            "TR_NoFundsOrGas",
                            EVMError::Transaction(InvalidTransaction::CallGasCostMoreThanGasLimit)
                        ) | (
                            "IntrinsicGas",
                            EVMError::Transaction(InvalidTransaction::CallGasCostMoreThanGasLimit)
                        )
                    ) {
                        panic!("\nUnmatched error!\nExpected: {:?}\nGot: {:?}", exception, error);
                    }
                }
                // Tests that exepect execution to succeed -> match post state root
                (None, Ok(exec_results)) => {
                    // TODO: We really should test with blocks with more than 1 tx
                    assert!(exec_results.len() == 1);
                    let ResultAndState { result, state } = exec_results[0].clone();

                    let logs_root = log_rlp_hash(result.logs());
                    assert_eq!(logs_root, test.logs);

                    for (address, account) in state {
                        if account.is_empty() {
                            continue;
                        }
                        chain_state.insert(
                            address,
                            PlainAccount {
                                info: account.info,
                                storage: account
                                    .storage
                                    .iter()
                                    .map(|(k, v)| (*k, v.present_value))
                                    .collect(),
                            },
                        );
                    }
                    let state_root =
                        state_merkle_trie_root(chain_state.iter().map(|(k, v)| (*k, v)));
                    assert_eq!(state_root, test.hash);
                }
                _ => {
                    panic!("BlockSTM result doesn't match the test's expectation.")
                }
            }
        }
    }
}

fn should_skip_test(path: &Path) -> bool {
    [
        // These tests are passed but time consuming, uncomment to skip them:
        // "stTimeConsuming/CALLBlake2f_MaxRounds.json",
        // "stTimeConsuming/static_Call50000_sha256.json",
        // "vmPerformance/loopMul.json",
        // "stQuadraticComplexityTest/Call50000_sha256.json",

        // failed and time consuming
        "stTimeConsuming/sstore_combinations_initial00_2_Paris.json",
        "stTimeConsuming/sstore_combinations_initial00_2.json",
        "stTimeConsuming/sstore_combinations_initial00_Paris.json",
        "stTimeConsuming/sstore_combinations_initial00.json",
        "stTimeConsuming/sstore_combinations_initial01_2_Paris.json",
        "stTimeConsuming/sstore_combinations_initial01_2.json",
        "stTimeConsuming/sstore_combinations_initial01_Paris.json",
        "stTimeConsuming/sstore_combinations_initial01.json",
        "stTimeConsuming/sstore_combinations_initial10_2_Paris.json",
        "stTimeConsuming/sstore_combinations_initial10_2.json",
        "stTimeConsuming/sstore_combinations_initial10_Paris.json",
        "stTimeConsuming/sstore_combinations_initial10.json",
        "stTimeConsuming/sstore_combinations_initial11_2_Paris.json",
        "stTimeConsuming/sstore_combinations_initial11_2.json",
        "stTimeConsuming/sstore_combinations_initial11_Paris.json",
        "stTimeConsuming/sstore_combinations_initial11.json",
        "stTimeConsuming/sstore_combinations_initial20_2_Paris.json",
        "stTimeConsuming/sstore_combinations_initial20_2.json",
        "stTimeConsuming/sstore_combinations_initial20_Paris.json",
        "stTimeConsuming/sstore_combinations_initial20.json",
        "stTimeConsuming/sstore_combinations_initial21_2_Paris.json",
        "stTimeConsuming/sstore_combinations_initial21_2.json",
        "stTimeConsuming/sstore_combinations_initial21_Paris.json",
        "stTimeConsuming/sstore_combinations_initial21.json",

        // failed
        "Cancun/stEIP1153-transientStorage/01_tloadBeginningTxn.json",
        "Cancun/stEIP1153-transientStorage/03_tloadAfterStoreIs0.json",
        "Cancun/stEIP1153-transientStorage/04_tloadAfterCall.json",
        "Cancun/stEIP1153-transientStorage/08_revertUndoesTransientStore.json",
        "Cancun/stEIP1153-transientStorage/09_revertUndoesAll.json",
        "Cancun/stEIP1153-transientStorage/10_revertUndoesStoreAfterReturn.json",
        "Cancun/stEIP1153-transientStorage/11_tstoreDelegateCall.json",
        "Cancun/stEIP1153-transientStorage/13_tloadStaticCall.json",
        "Cancun/stEIP1153-transientStorage/14_revertAfterNestedStaticcall.json",
        "Cancun/stEIP1153-transientStorage/15_tstoreCannotBeDosd.json",
        "Cancun/stEIP1153-transientStorage/18_tloadAfterStore.json",
        "Cancun/stEIP1153-transientStorage/19_oogUndoesTransientStore.json",
        "Cancun/stEIP1153-transientStorage/20_oogUndoesTransientStoreInCall.json",
        "Cancun/stEIP1153-transientStorage/21_tstoreCannotBeDosdOOO.json",
        "Cancun/stEIP1153-transientStorage/transStorageOK.json",
        "Cancun/stEIP1153-transientStorage/transStorageReset.json",
        "Cancun/stEIP4844-blobtransactions/opcodeBlobhashOutOfRange.json",
        "Cancun/stEIP4844-blobtransactions/opcodeBlobhBounds.json",
        "Cancun/stEIP5656-MCOPY/MCOPY_memory_expansion_cost.json",
        "Pyspecs/cancun/eip1153_tstore/reentrant_selfdestructing_call.json",
        "Pyspecs/cancun/eip1153_tstore/tload_after_sstore.json",
        "Pyspecs/cancun/eip1153_tstore/tload_after_tstore_is_zero.json",
        "Pyspecs/cancun/eip1153_tstore/tload_after_tstore.json",
        "Pyspecs/cancun/eip1153_tstore/transient_storage_unset_values.json",
        "Pyspecs/cancun/eip6780_selfdestruct/create_selfdestruct_same_tx.json",
        "Pyspecs/cancun/eip6780_selfdestruct/delegatecall_from_new_contract_to_pre_existing_contract.json",
        "Pyspecs/cancun/eip6780_selfdestruct/delegatecall_from_pre_existing_contract_to_new_contract.json",
        "Pyspecs/cancun/eip6780_selfdestruct/dynamic_create2_selfdestruct_collision.json",
        "Pyspecs/cancun/eip6780_selfdestruct/reentrancy_selfdestruct_revert.json",
        "Pyspecs/cancun/eip6780_selfdestruct/self_destructing_initcode_create_tx.json",
        "Pyspecs/cancun/eip6780_selfdestruct/self_destructing_initcode.json",
        "Pyspecs/cancun/eip6780_selfdestruct/selfdestruct_created_in_same_tx_with_revert.json",
        "Pyspecs/cancun/eip6780_selfdestruct/selfdestruct_pre_existing.json",
        "Pyspecs/cancun/eip7516_blobgasfee/blobbasefee_before_fork.json",
        "Pyspecs/shanghai/eip3855_push0/push0_storage_overwrite.json",
        "Shanghai/stEIP3855-push0/push0.json",
        "stArgsZeroOneBalance/suicideNonConst.json",
        "stAttackTest/CrashingTransaction.json",
        "stBadOpcode/invalidAddr.json",
        "stBadOpcode/invalidDiffPlaces.json",
        "stBadOpcode/opc0CDiffPlaces.json",
        "stBadOpcode/opc0DDiffPlaces.json",
        "stBadOpcode/opc0EDiffPlaces.json",
        "stBadOpcode/opc0FDiffPlaces.json",
        "stBadOpcode/opc1EDiffPlaces.json",
        "stBadOpcode/opc1FDiffPlaces.json",
        "stBadOpcode/opc21DiffPlaces.json",
        "stBadOpcode/opc22DiffPlaces.json",
        "stBadOpcode/opc23DiffPlaces.json",
        "stBadOpcode/opc24DiffPlaces.json",
        "stBadOpcode/opc25DiffPlaces.json",
        "stBadOpcode/opc26DiffPlaces.json",
        "stBadOpcode/opc27DiffPlaces.json",
        "stBadOpcode/opc28DiffPlaces.json",
        "stBadOpcode/opc29DiffPlaces.json",
        "stBadOpcode/opc2ADiffPlaces.json",
        "stBadOpcode/opc2BDiffPlaces.json",
        "stBadOpcode/opc2CDiffPlaces.json",
        "stBadOpcode/opc2DDiffPlaces.json",
        "stBadOpcode/opc2EDiffPlaces.json",
        "stBadOpcode/opc2FDiffPlaces.json",
        "stBadOpcode/opc49DiffPlaces.json",
        "stBadOpcode/opc4ADiffPlaces.json",
        "stBadOpcode/opc4BDiffPlaces.json",
        "stBadOpcode/opc4CDiffPlaces.json",
        "stBadOpcode/opc4DDiffPlaces.json",
        "stBadOpcode/opc4EDiffPlaces.json",
        "stBadOpcode/opc4FDiffPlaces.json",
        "stBadOpcode/opc5CDiffPlaces.json",
        "stBadOpcode/opc5DDiffPlaces.json",
        "stBadOpcode/opc5EDiffPlaces.json",
        "stBadOpcode/opc5FDiffPlaces.json",
        "stBadOpcode/opcA5DiffPlaces.json",
        "stBadOpcode/opcA6DiffPlaces.json",
        "stBadOpcode/opcA7DiffPlaces.json",
        "stBadOpcode/opcA8DiffPlaces.json",
        "stBadOpcode/opcA9DiffPlaces.json",
        "stBadOpcode/opcAADiffPlaces.json",
        "stBadOpcode/opcABDiffPlaces.json",
        "stBadOpcode/opcACDiffPlaces.json",
        "stBadOpcode/opcADDiffPlaces.json",
        "stBadOpcode/opcAEDiffPlaces.json",
        "stBadOpcode/opcAFDiffPlaces.json",
        "stBadOpcode/opcB0DiffPlaces.json",
        "stBadOpcode/opcB1DiffPlaces.json",
        "stBadOpcode/opcB2DiffPlaces.json",
        "stBadOpcode/opcB3DiffPlaces.json",
        "stBadOpcode/opcB4DiffPlaces.json",
        "stBadOpcode/opcB5DiffPlaces.json",
        "stBadOpcode/opcB6DiffPlaces.json",
        "stBadOpcode/opcB7DiffPlaces.json",
        "stBadOpcode/opcB8DiffPlaces.json",
        "stBadOpcode/opcB9DiffPlaces.json",
        "stBadOpcode/opcBADiffPlaces.json",
        "stBadOpcode/opcBBDiffPlaces.json",
        "stBadOpcode/opcBCDiffPlaces.json",
        "stBadOpcode/opcBDDiffPlaces.json",
        "stBadOpcode/opcBEDiffPlaces.json",
        "stBadOpcode/opcBFDiffPlaces.json",
        "stBadOpcode/opcC0DiffPlaces.json",
        "stBadOpcode/opcC1DiffPlaces.json",
        "stBadOpcode/opcC2DiffPlaces.json",
        "stBadOpcode/opcC3DiffPlaces.json",
        "stBadOpcode/opcC4DiffPlaces.json",
        "stBadOpcode/opcC5DiffPlaces.json",
        "stBadOpcode/opcC6DiffPlaces.json",
        "stBadOpcode/opcC7DiffPlaces.json",
        "stBadOpcode/opcC8DiffPlaces.json",
        "stBadOpcode/opcC9DiffPlaces.json",
        "stBadOpcode/opcCADiffPlaces.json",
        "stBadOpcode/opcCBDiffPlaces.json",
        "stBadOpcode/opcCCDiffPlaces.json",
        "stBadOpcode/opcCDDiffPlaces.json",
        "stBadOpcode/opcCEDiffPlaces.json",
        "stBadOpcode/opcCFDiffPlaces.json",
        "stBadOpcode/opcD0DiffPlaces.json",
        "stBadOpcode/opcD1DiffPlaces.json",
        "stBadOpcode/opcD2DiffPlaces.json",
        "stBadOpcode/opcD3DiffPlaces.json",
        "stBadOpcode/opcD4DiffPlaces.json",
        "stBadOpcode/opcD5DiffPlaces.json",
        "stBadOpcode/opcD6DiffPlaces.json",
        "stBadOpcode/opcD7DiffPlaces.json",
        "stBadOpcode/opcD8DiffPlaces.json",
        "stBadOpcode/opcD9DiffPlaces.json",
        "stBadOpcode/opcDADiffPlaces.json",
        "stBadOpcode/opcDBDiffPlaces.json",
        "stBadOpcode/opcDCDiffPlaces.json",
        "stBadOpcode/opcDDDiffPlaces.json",
        "stBadOpcode/opcDEDiffPlaces.json",
        "stBadOpcode/opcDFDiffPlaces.json",
        "stBadOpcode/opcE0DiffPlaces.json",
        "stBadOpcode/opcE1DiffPlaces.json",
        "stBadOpcode/opcE2DiffPlaces.json",
        "stBadOpcode/opcE3DiffPlaces.json",
        "stBadOpcode/opcE4DiffPlaces.json",
        "stBadOpcode/opcE5DiffPlaces.json",
        "stBadOpcode/opcE6DiffPlaces.json",
        "stBadOpcode/opcE7DiffPlaces.json",
        "stBadOpcode/opcE8DiffPlaces.json",
        "stBadOpcode/opcE9DiffPlaces.json",
        "stBadOpcode/opcEADiffPlaces.json",
        "stBadOpcode/opcEBDiffPlaces.json",
        "stBadOpcode/opcECDiffPlaces.json",
        "stBadOpcode/opcEDDiffPlaces.json",
        "stBadOpcode/opcEEDiffPlaces.json",
        "stBadOpcode/opcEFDiffPlaces.json",
        "stBadOpcode/opcF6DiffPlaces.json",
        "stBadOpcode/opcF7DiffPlaces.json",
        "stBadOpcode/opcF8DiffPlaces.json",
        "stBadOpcode/opcF9DiffPlaces.json",
        "stBadOpcode/opcFBDiffPlaces.json",
        "stBadOpcode/opcFCDiffPlaces.json",
        "stBadOpcode/opcFEDiffPlaces.json",
        "stBugs/randomStatetestDEFAULT-Tue_07_58_41-15153-575192_london.json",
        "stBugs/randomStatetestDEFAULT-Tue_07_58_41-15153-575192.json",
        "stBugs/staticcall_createfails.json",
        "stCallCodes/call_OOG_additionalGasCosts2.json",
        "stCallCodes/callcall_00_SuicideEnd.json",
        "stCallCodes/callcallcall_000_SuicideEnd.json",
        "stCallCodes/callcallcall_000_SuicideMiddle.json",
        "stCallCodes/callcallcallcode_001_SuicideEnd.json",
        "stCallCodes/callcallcallcode_001_SuicideMiddle.json",
        "stCallCodes/callcallcode_01_SuicideEnd.json",
        "stCallCodes/callcallcodecall_010_SuicideEnd.json",
        "stCallCodes/callcallcodecall_010_SuicideMiddle.json",
        "stCallCodes/callcallcodecallcode_011_SuicideEnd.json",
        "stCallCodes/callcallcodecallcode_011_SuicideMiddle.json",
        "stCallCodes/callcodecall_10_SuicideEnd.json",
        "stCallCodes/callcodecallcall_100_SuicideEnd.json",
        "stCallCodes/callcodecallcall_100_SuicideMiddle.json",
        "stCallCodes/callcodecallcallcode_101_SuicideEnd.json",
        "stCallCodes/callcodecallcallcode_101_SuicideMiddle.json",
        "stCallCodes/callcodecallcode_11_SuicideEnd.json",
        "stCallCodes/callcodecallcodecall_110_SuicideEnd.json",
        "stCallCodes/callcodecallcodecall_110_SuicideMiddle.json",
        "stCallCodes/callcodecallcodecallcode_111_SuicideEnd.json",
        "stCallCodes/callcodecallcodecallcode_111_SuicideMiddle.json",
        "stCallCodes/touchAndGo.json",
        "stCallCreateCallCodeTest/callWithHighValueAndGasOOG.json",
        "stCallCreateCallCodeTest/callWithHighValueAndOOGatTxLevel.json",
        "stCallCreateCallCodeTest/createFailBalanceTooLow.json",
        "stCallCreateCallCodeTest/createInitFailBadJumpDestination.json",
        "stCallCreateCallCodeTest/createInitFailBadJumpDestination2.json",
        "stCallCreateCallCodeTest/createInitFailStackSizeLargerThan1024.json",
        "stCallCreateCallCodeTest/createInitFailStackUnderflow.json",
        "stCallCreateCallCodeTest/createInitFailUndefinedInstruction2.json",
        "stCallCreateCallCodeTest/createInitOOGforCREATE.json",
        "stCallCreateCallCodeTest/createJS_ExampleContract.json",
        "stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcallcallcode_001_SuicideMiddle.json",
        "stCallDelegateCodesCallCodeHomestead/callcallcode_01_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcallcodecall_010_SuicideMiddle.json",
        "stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcallcodecallcode_011_SuicideMiddle.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecall_10_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcall_100_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcall_100_SuicideMiddle.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcallcode_101_SuicideMiddle.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcode_11_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcodecall_110_SuicideMiddle.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_111_SuicideEnd.json",
        "stCallDelegateCodesCallCodeHomestead/callcodecallcodecallcode_111_SuicideMiddle.json",
        "stCallDelegateCodesHomestead/callcallcallcode_001_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcallcallcode_001_SuicideMiddle.json",
        "stCallDelegateCodesHomestead/callcallcode_01_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcallcodecall_010_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcallcodecall_010_SuicideMiddle.json",
        "stCallDelegateCodesHomestead/callcallcodecallcode_011_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcallcodecallcode_011_SuicideMiddle.json",
        "stCallDelegateCodesHomestead/callcodecall_10_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcodecallcall_100_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcodecallcall_100_SuicideMiddle.json",
        "stCallDelegateCodesHomestead/callcodecallcallcode_101_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcodecallcallcode_101_SuicideMiddle.json",
        "stCallDelegateCodesHomestead/callcodecallcode_11_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcodecallcodecall_110_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcodecallcodecall_110_SuicideMiddle.json",
        "stCallDelegateCodesHomestead/callcodecallcodecallcode_111_SuicideEnd.json",
        "stCallDelegateCodesHomestead/callcodecallcodecallcode_111_SuicideMiddle.json",
        "stCreate2/call_outsize_then_create2_successful_then_returndatasize.json",
        "stCreate2/call_then_create2_successful_then_returndatasize.json",
        "stCreate2/CREATE2_ContractSuicideDuringInit_ThenStoreThenReturn.json",
        "stCreate2/CREATE2_HighNonceDelegatecall.json",
        "stCreate2/CREATE2_Suicide.json",
        "stCreate2/create2collisionSelfdestructed.json",
        "stCreate2/create2collisionSelfdestructed2.json",
        "stCreate2/create2collisionStorage.json",
        "stCreate2/create2collisionStorageParis.json",
        "stCreate2/create2InitCodes.json",
        "stCreate2/Create2OOGafterInitCodeReturndata.json",
        "stCreate2/Create2OOGafterInitCodeReturndata2.json",
        "stCreate2/Create2OOGafterInitCodeReturndata3.json",
        "stCreate2/Create2OOGafterInitCodeRevert.json",
        "stCreate2/Create2OOGafterInitCodeRevert2.json",
        "stCreate2/Create2OOGFromCallRefunds.json",
        "stCreate2/create2SmartInitCode.json",
        "stCreate2/returndatacopy_0_0_following_successful_create.json",
        "stCreate2/returndatacopy_afterFailing_create.json",
        "stCreate2/returndatacopy_following_create.json",
        "stCreate2/returndatacopy_following_revert_in_create.json",
        "stCreate2/returndatacopy_following_successful_create.json",
        "stCreate2/returndatasize_following_successful_create.json",
        "stCreate2/RevertInCreateInInitCreate2.json",
        "stCreate2/RevertInCreateInInitCreate2Paris.json",
        "stCreate2/RevertOpcodeInCreateReturnsCreate2.json",
        "stCreateTest/CodeInConstructor.json",
        "stCreateTest/CREATE_AcreateB_BSuicide_BStore.json",
        "stCreateTest/CREATE_ContractSuicideDuringInit_ThenStoreThenReturn.json",
        "stCreateTest/CREATE_ContractSuicideDuringInit_WithValue.json",
        "stCreateTest/CREATE_ContractSuicideDuringInit_WithValueToItself.json",
        "stCreateTest/CREATE_ContractSuicideDuringInit.json",
        "stCreateTest/CREATE2_RefundEF.json",
        "stCreateTest/CreateCollisionResults.json",
        "stCreateTest/createLargeResult.json",
        "stCreateTest/CreateOOGafterInitCodeRevert2.json",
        "stCreateTest/CreateOOGafterMaxCodesize.json",
        "stCreateTest/CreateOOGFromCallRefunds.json",
        "stCreateTest/CreateOOGFromEOARefunds.json",
        "stCreateTest/CreateResults.json",
        "stCreateTest/CreateTransactionHighNonce.json",
        "stCreateTest/CreateTransactionRefundEF.json",
        "stEIP150singleCodeGasPrices/eip2929-ff.json",
        "stEIP150singleCodeGasPrices/eip2929.json",
        "stEIP150singleCodeGasPrices/eip2929OOG.json",
        "stEIP150singleCodeGasPrices/gasCost.json",
        "stEIP150singleCodeGasPrices/gasCostBerlin.json",
        "stEIP150singleCodeGasPrices/gasCostExp.json",
        "stEIP150singleCodeGasPrices/gasCostJump.json",
        "stEIP150singleCodeGasPrices/gasCostMemory.json",
        "stEIP150singleCodeGasPrices/gasCostMemSeg.json",
        "stEIP150singleCodeGasPrices/gasCostReturn.json",
        "stEIP150Specific/NewGasPriceForCodes.json",
        "stEIP150Specific/SuicideToExistingContract.json",
        "stEIP150Specific/SuicideToNotExistingContract.json",
        "stEIP1559/baseFeeDiffPlaces.json",
        "stEIP1559/gasPriceDiffPlaces.json",
        "stEIP1559/lowGasLimit.json",
        "stEIP1559/typeTwoBerlin.json",
        "stEIP158Specific/CALL_OneVCallSuicide.json",
        "stEIP158Specific/CALL_OneVCallSuicide2.json",
        "stEIP158Specific/CALL_ZeroVCallSuicide.json",
        "stEIP158Specific/callToEmptyThenCallError.json",
        "stEIP158Specific/EXTCODESIZE_toEpmtyParis.json",
        "stEIP158Specific/vitalikTransactionTest.json",
        "stEIP158Specific/vitalikTransactionTestParis.json",
        "stEIP2930/storageCosts.json",
        "stEIP2930/variedContext.json",
        "stExample/basefeeExample.json",
        "stExample/eip1559.json",
        "stExtCodeHash/callToNonExistent.json",
        "stExtCodeHash/callToSuicideThenExtcodehash.json",
        "stExtCodeHash/createEmptyThenExtcodehash.json",
        "stExtCodeHash/dynamicAccountOverwriteEmpty_Paris.json",
        "stExtCodeHash/dynamicAccountOverwriteEmpty.json",
        "stExtCodeHash/extCodeHashCALL.json",
        "stExtCodeHash/extCodeHashCALLCODE.json",
        "stExtCodeHash/extCodeHashCreatedAndDeletedAccount.json",
        "stExtCodeHash/extCodeHashCreatedAndDeletedAccountCall.json",
        "stExtCodeHash/extCodeHashCreatedAndDeletedAccountRecheckInOuterCall.json",
        "stExtCodeHash/extCodeHashDELEGATECALL.json",
        "stExtCodeHash/extCodeHashDeletedAccount.json",
        "stExtCodeHash/extCodeHashDeletedAccount1.json",
        "stExtCodeHash/extCodeHashDeletedAccount1Cancun.json",
        "stExtCodeHash/extCodeHashDeletedAccount2.json",
        "stExtCodeHash/extCodeHashDeletedAccount2Cancun.json",
        "stExtCodeHash/extCodeHashDeletedAccount3.json",
        "stExtCodeHash/extCodeHashDeletedAccount4.json",
        "stExtCodeHash/extCodeHashDeletedAccountCancun.json",
        "stExtCodeHash/extCodeHashDynamicArgument.json",
        "stExtCodeHash/extcodehashEmpty_Paris.json",
        "stExtCodeHash/extcodehashEmpty.json",
        "stExtCodeHash/extCodeHashPrecompiles.json",
        "stExtCodeHash/extCodeHashSelf.json",
        "stExtCodeHash/extCodeHashSelfInInit.json",
        "stExtCodeHash/extCodeHashSTATICCALL.json",
        "stExtCodeHash/extCodeHashSubcallSuicide.json",
        "stExtCodeHash/extCodeHashSubcallSuicideCancun.json",
        "stInitCodeTest/TransactionCreateSuicideInInitcode.json",
        "stMemExpandingEIP150Calls/NewGasPriceForCodesWithMemExpandingCalls.json",
        "stMemoryTest/buffer.json",
        "stMemoryTest/bufferSrcOffset.json",
        "stMemoryTest/memCopySelf.json",
        "stNonZeroCallsTest/NonZeroValue_CALL_ToOneStorageKey_Paris.json",
        "stNonZeroCallsTest/NonZeroValue_CALL_ToOneStorageKey.json",
        "stNonZeroCallsTest/NonZeroValue_CALLCODE_ToOneStorageKey_Paris.json",
        "stNonZeroCallsTest/NonZeroValue_CALLCODE_ToOneStorageKey.json",
        "stNonZeroCallsTest/NonZeroValue_DELEGATECALL_ToOneStorageKey_Paris.json",
        "stNonZeroCallsTest/NonZeroValue_DELEGATECALL_ToOneStorageKey.json",
        "stNonZeroCallsTest/NonZeroValue_SUICIDE_ToEmpty_Paris.json",
        "stNonZeroCallsTest/NonZeroValue_SUICIDE_ToEmpty.json",
        "stNonZeroCallsTest/NonZeroValue_SUICIDE_ToNonNonZeroBalance.json",
        "stNonZeroCallsTest/NonZeroValue_SUICIDE_ToOneStorageKey_Paris.json",
        "stNonZeroCallsTest/NonZeroValue_SUICIDE_ToOneStorageKey.json",
        "stNonZeroCallsTest/NonZeroValue_SUICIDE.json",
        "stNonZeroCallsTest/NonZeroValue_TransactionCALL_ToOneStorageKey_Paris.json",
        "stNonZeroCallsTest/NonZeroValue_TransactionCALL_ToOneStorageKey.json",
        "stNonZeroCallsTest/NonZeroValue_TransactionCALLwithData_ToOneStorageKey_Paris.json",
        "stNonZeroCallsTest/NonZeroValue_TransactionCALLwithData_ToOneStorageKey.json",
        "stPreCompiledContracts/delegatecall09Undefined.json",
        "stPreCompiledContracts/precompsEIP2929.json",
        "stPreCompiledContracts/precompsEIP2929Cancun.json",
        "stPreCompiledContracts2/CALLCODEEcrecover0_NoGas.json",
        "stPreCompiledContracts2/CallEcrecover_Overflow.json",
        "stPreCompiledContracts2/CallEcrecover0_NoGas.json",
        "stPreCompiledContracts2/ecrecoverShortBuff.json",
        "stPreCompiledContracts2/ecrecoverWeirdV.json",
        "stRandom/randomStatetest14.json",
        "stRandom/randomStatetest147.json",
        "stRandom/randomStatetest173.json",
        "stRandom/randomStatetest198.json",
        "stRandom/randomStatetest201.json",
        "stRandom/randomStatetest212.json",
        "stRandom/randomStatetest22.json",
        "stRandom/randomStatetest232.json",
        "stRandom/randomStatetest273.json",
        "stRandom/randomStatetest282.json",
        "stRandom/randomStatetest287.json",
        "stRandom/randomStatetest376.json",
        "stRandom2/randomStatetest401.json",
        "stRandom2/randomStatetest409.json",
        "stRandom2/randomStatetest487.json",
        "stRandom2/randomStatetest495.json",
        "stRandom2/randomStatetest559.json",
        "stRandom2/randomStatetest581.json",
        "stRandom2/randomStatetest635.json",
        "stRefundTest/refund_CallA_notEnoughGasInCall.json",
        "stRefundTest/refund_CallA_OOG.json",
        "stRefundTest/refund_CallA.json",
        "stRefundTest/refund_CallToSuicideNoStorage.json",
        "stRefundTest/refund_CallToSuicideStorage.json",
        "stRefundTest/refund_CallToSuicideTwice.json",
        "stRefundTest/refund_changeNonZeroStorage.json",
        "stRefundTest/refund_getEtherBack.json",
        "stRefundTest/refund_multimpleSuicide.json",
        "stRefundTest/refund_NoOOG_1.json",
        "stRefundTest/refund_OOG.json",
        "stRefundTest/refund_singleSuicide.json",
        "stRefundTest/refund_TxToSuicide.json",
        "stRefundTest/refund_TxToSuicideOOG.json",
        "stRefundTest/refund50_1.json",
        "stRefundTest/refund50_2.json",
        "stRefundTest/refund50percentCap.json",
        "stRefundTest/refund600.json",
        "stRefundTest/refundFF.json",
        "stRefundTest/refundMax.json",
        "stRefundTest/refundResetFrontier.json",
        "stRefundTest/refundSSTORE.json",
        "stRefundTest/refundSuicide50procentCap.json",
        "stReturnDataTest/call_ecrec_success_empty_then_returndatasize.json",
        "stReturnDataTest/call_outsize_then_create_successful_then_returndatasize.json",
        "stReturnDataTest/call_then_call_value_fail_then_returndatasize.json",
        "stReturnDataTest/call_then_create_successful_then_returndatasize.json",
        "stReturnDataTest/clearReturnBuffer.json",
        "stReturnDataTest/create_callprecompile_returndatasize.json",
        "stReturnDataTest/modexp_modsize0_returndatasize.json",
        "stReturnDataTest/returndatacopy_0_0_following_successful_create.json",
        "stReturnDataTest/returndatacopy_after_failing_callcode.json",
        "stReturnDataTest/returndatacopy_after_failing_delegatecall.json",
        "stReturnDataTest/returndatacopy_after_failing_staticcall.json",
        "stReturnDataTest/returndatacopy_after_revert_in_staticcall.json",
        "stReturnDataTest/returndatacopy_after_successful_callcode.json",
        "stReturnDataTest/returndatacopy_after_successful_delegatecall.json",
        "stReturnDataTest/returndatacopy_after_successful_staticcall.json",
        "stReturnDataTest/returndatacopy_afterFailing_create.json",
        "stReturnDataTest/returndatacopy_following_call.json",
        "stReturnDataTest/returndatacopy_following_create.json",
        "stReturnDataTest/returndatacopy_following_failing_call.json",
        "stReturnDataTest/returndatacopy_following_revert_in_create.json",
        "stReturnDataTest/returndatacopy_following_revert.json",
        "stReturnDataTest/returndatacopy_following_successful_create.json",
        "stReturnDataTest/returndatacopy_following_too_big_transfer.json",
        "stReturnDataTest/returndatacopy_initial_256.json",
        "stReturnDataTest/returndatacopy_initial_big_sum.json",
        "stReturnDataTest/returndatacopy_initial.json",
        "stReturnDataTest/returndatacopy_overrun.json",
        "stReturnDataTest/returndatasize_after_failing_callcode.json",
        "stReturnDataTest/returndatasize_after_failing_delegatecall.json",
        "stReturnDataTest/returndatasize_after_failing_staticcall.json",
        "stReturnDataTest/returndatasize_after_oog_after_deeper.json",
        "stReturnDataTest/returndatasize_after_successful_delegatecall.json",
        "stReturnDataTest/returndatasize_after_successful_staticcall.json",
        "stReturnDataTest/returndatasize_bug.json",
        "stReturnDataTest/returndatasize_following_successful_create.json",
        "stReturnDataTest/returndatasize_initial_zero_read.json",
        "stReturnDataTest/returndatasize_initial.json",
        "stReturnDataTest/revertRetDataSize.json",
        "stReturnDataTest/tooLongReturnDataCopy.json",
        "stRevertTest/LoopCallsThenRevert.json",
        "stRevertTest/RevertInCreateInInit_Paris.json",
        "stRevertTest/RevertInCreateInInit.json",
        "stRevertTest/RevertOpcodeInCallsOnNonEmptyReturnData.json",
        "stRevertTest/RevertOpcodeInCreateReturns.json",
        "stRevertTest/RevertPrecompiledTouch_noncestorage.json",
        "stRevertTest/RevertPrecompiledTouch_storage_Paris.json",
        "stRevertTest/RevertPrecompiledTouch_storage.json",
        "stRevertTest/RevertPrecompiledTouch.json",
        "stRevertTest/RevertPrecompiledTouchExactOOG.json",
        "stRevertTest/RevertPrefoundEmptyCall.json",
        "stRevertTest/RevertRemoteSubCallStorageOOG.json",
        "stRevertTest/TouchToEmptyAccountRevert2.json",
        "stRevertTest/TouchToEmptyAccountRevert3_Paris.json",
        "stRevertTest/TouchToEmptyAccountRevert3.json",
        "stSelfBalance/diffPlaces.json",
        "stSelfBalance/selfBalanceCallTypes.json",
        "stShift/sar_0_256-1.json",
        "stShift/sar_2^254_254.json",
        "stShift/sar_2^255_1.json",
        "stShift/sar_2^255_255.json",
        "stShift/sar_2^255_256.json",
        "stShift/sar_2^255_257.json",
        "stShift/sar_2^255-1_248.json",
        "stShift/sar_2^255-1_254.json",
        "stShift/sar_2^255-1_255.json",
        "stShift/sar_2^255-1_256.json",
        "stShift/sar_2^256-1_0.json",
        "stShift/sar_2^256-1_1.json",
        "stShift/sar_2^256-1_255.json",
        "stShift/sar_2^256-1_256.json",
        "stShift/sar00.json",
        "stShift/sar01.json",
        "stShift/sar10.json",
        "stShift/sar11.json",
        "stShift/shl_-1_0.json",
        "stShift/shl_-1_1.json",
        "stShift/shl_-1_255.json",
        "stShift/shl_-1_256.json",
        "stShift/shl_2^255-1_1.json",
        "stShift/shl01-0100.json",
        "stShift/shl01-0101.json",
        "stShift/shl01-ff.json",
        "stShift/shl01.json",
        "stShift/shl10.json",
        "stShift/shl11.json",
        "stShift/shr_-1_0.json",
        "stShift/shr_-1_1.json",
        "stShift/shr_-1_255.json",
        "stShift/shr_-1_256.json",
        "stShift/shr_2^255_1.json",
        "stShift/shr_2^255_255.json",
        "stShift/shr_2^255_256.json",
        "stShift/shr_2^255_257.json",
        "stShift/shr01.json",
        "stShift/shr10.json",
        "stShift/shr11.json",
        "stSolidityTest/SelfDestruct.json",
        "stSolidityTest/TestContractSuicide.json",
        "stSpecialTest/block504980.json",
        "stSpecialTest/eoaEmpty.json",
        "stSpecialTest/eoaEmptyParis.json",
        "stSpecialTest/failed_tx_xcf416c53.json",
        "stSpecialTest/FailedCreateRevertsDeletion.json",
        "stSpecialTest/FailedCreateRevertsDeletionParis.json",
        "stSpecialTest/selfdestructEIP2929.json",
        "stSpecialTest/tx_e1c174e2.json",
        "stSStoreTest/InitCollision.json",
        "stSStoreTest/InitCollisionNonZeroNonce.json",
        "stSStoreTest/InitCollisionParis.json",
        "stSStoreTest/sstore_changeFromExternalCallInInitCode.json",
        "stSStoreTest/sstore_gasLeft.json",
        "stSStoreTest/sstore_Xto0.json",
        "stSStoreTest/sstore_Xto0to0.json",
        "stSStoreTest/sstore_Xto0toX.json",
        "stSStoreTest/sstore_Xto0toXto0.json",
        "stSStoreTest/sstore_Xto0toY.json",
        "stSStoreTest/sstore_XtoX.json",
        "stSStoreTest/sstore_XtoXto0.json",
        "stSStoreTest/sstore_XtoXtoX.json",
        "stSStoreTest/sstore_XtoXtoY.json",
        "stSStoreTest/sstore_XtoY.json",
        "stSStoreTest/sstore_XtoYto0.json",
        "stSStoreTest/sstore_XtoYtoX.json",
        "stSStoreTest/sstore_XtoYtoY.json",
        "stSStoreTest/sstore_XtoYtoZ.json",
        "stSStoreTest/SstoreCallToSelfSubRefundBelowZero.json",
        "stSStoreTest/sstoreGas.json",
        "stStackTests/underflowTest.json",
        "stStaticCall/static_ABAcallsSuicide0.json",
        "stStaticCall/static_call_value_inherit_from_call.json",
        "stStaticCall/static_call_value_inherit.json",
        "stStaticCall/static_Call50000.json",
        "stStaticCall/static_callBasic.json",
        "stStaticCall/static_callcodecall_10_SuicideEnd.json",
        "stStaticCall/static_callcodecall_10_SuicideEnd2.json",
        "stStaticCall/static_callcodecallcodecall_110_SuicideEnd.json",
        "stStaticCall/static_callcodecallcodecall_110_SuicideEnd2.json",
        "stStaticCall/static_callcodecallcodecall_110_SuicideMiddle.json",
        "stStaticCall/static_callcodecallcodecall_110_SuicideMiddle2.json",
        "stStaticCall/static_callWithHighValueAndGasOOG.json",
        "stStaticCall/static_CREATE_ContractSuicideDuringInit_ThenStoreThenReturn.json",
        "stStaticCall/static_CREATE_ContractSuicideDuringInit_WithValue.json",
        "stStaticCall/static_CREATE_ContractSuicideDuringInit.json",
        "stStaticCall/static_InternlCallStoreClearsOOG.json",
        "stStaticCall/static_LoopCallsThenRevert.json",
        "stStaticCall/static_refund_CallA.json",
        "stStaticCall/static_refund_CallToSuicideNoStorage.json",
        "stStaticCall/static_refund_CallToSuicideTwice.json",
        "stStaticFlagEnabled/CallcodeToPrecompileFromCalledContract.json",
        "stStaticFlagEnabled/CallcodeToPrecompileFromContractInitialization.json",
        "stStaticFlagEnabled/CallcodeToPrecompileFromTransaction.json",
        "stStaticFlagEnabled/CallWithNOTZeroValueToPrecompileFromCalledContract.json",
        "stStaticFlagEnabled/CallWithNOTZeroValueToPrecompileFromContractInitialization.json",
        "stStaticFlagEnabled/CallWithNOTZeroValueToPrecompileFromTransaction.json",
        "stStaticFlagEnabled/CallWithZeroValueToPrecompileFromCalledContract.json",
        "stStaticFlagEnabled/CallWithZeroValueToPrecompileFromContractInitialization.json",
        "stStaticFlagEnabled/CallWithZeroValueToPrecompileFromTransaction.json",
        "stStaticFlagEnabled/DelegatecallToPrecompileFromCalledContract.json",
        "stStaticFlagEnabled/DelegatecallToPrecompileFromContractInitialization.json",
        "stStaticFlagEnabled/DelegatecallToPrecompileFromTransaction.json",
        "stSystemOperationsTest/ABAcallsSuicide0.json",
        "stSystemOperationsTest/doubleSelfdestructTest.json",
        "stSystemOperationsTest/doubleSelfdestructTouch_Paris.json",
        "stSystemOperationsTest/doubleSelfdestructTouch.json",
        "stSystemOperationsTest/extcodecopy.json",
        "stSystemOperationsTest/multiSelfdestruct.json",
        "stSystemOperationsTest/suicideAddress.json",
        "stSystemOperationsTest/suicideCaller.json",
        "stSystemOperationsTest/suicideCallerAddresTooBigLeft.json",
        "stSystemOperationsTest/suicideCallerAddresTooBigRight.json",
        "stSystemOperationsTest/suicideNotExistingAccount.json",
        "stSystemOperationsTest/suicideOrigin.json",
        "stSystemOperationsTest/suicideSendEtherPostDeath.json",
        "stSystemOperationsTest/suicideSendEtherToMe.json",
        "stTransactionTest/ContractStoreClearsOOG.json",
        "stTransactionTest/ContractStoreClearsSuccess.json",
        "stTransactionTest/InternlCallStoreClearsOOG.json",
        "stTransactionTest/InternlCallStoreClearsSucces.json",
        "stTransactionTest/Opcodes_TransactionInit.json",
        "stTransactionTest/StoreClearsAndInternlCallStoreClearsOOG.json",
        "stTransactionTest/StoreClearsAndInternlCallStoreClearsSuccess.json",
        "stTransactionTest/SuicidesAndInternlCallSuicidesBonusGasAtCall.json",
        "stTransactionTest/SuicidesAndInternlCallSuicidesBonusGasAtCallFailed.json",
        "stTransactionTest/SuicidesAndInternlCallSuicidesSuccess.json",
        "stTransactionTest/SuicidesAndSendMoneyToItselfEtherDestroyed.json",
        "stTransactionTest/SuicidesStopAfterSuicide.json",
        "stTransactionTest/ValueOverflow.json",
        "stTransactionTest/ValueOverflowParis.json",
        "stWalletTest/dayLimitResetSpentToday.json",
        "stWalletTest/dayLimitSetDailyLimit.json",
        "stWalletTest/dayLimitSetDailyLimitNoData.json",
        "stWalletTest/multiOwnedAddOwner.json",
        "stWalletTest/multiOwnedAddOwnerAddMyself.json",
        "stWalletTest/multiOwnedChangeOwner_fromNotOwner.json",
        "stWalletTest/multiOwnedChangeOwner_toIsOwner.json",
        "stWalletTest/multiOwnedChangeOwner.json",
        "stWalletTest/multiOwnedChangeOwnerNoArgument.json",
        "stWalletTest/multiOwnedChangeRequirementTo0.json",
        "stWalletTest/multiOwnedChangeRequirementTo1.json",
        "stWalletTest/multiOwnedChangeRequirementTo2.json",
        "stWalletTest/multiOwnedIsOwnerFalse.json",
        "stWalletTest/multiOwnedIsOwnerTrue.json",
        "stWalletTest/multiOwnedRemoveOwner_mySelf.json",
        "stWalletTest/multiOwnedRemoveOwner_ownerIsNotOwner.json",
        "stWalletTest/multiOwnedRemoveOwner.json",
        "stWalletTest/multiOwnedRemoveOwnerByNonOwner.json",
        "stWalletTest/multiOwnedRevokeNothing.json",
        "stWalletTest/walletAddOwnerRemovePendingTransaction.json",
        "stWalletTest/walletChangeOwnerRemovePendingTransaction.json",
        "stWalletTest/walletChangeRequirementRemovePendingTransaction.json",
        "stWalletTest/walletConfirm.json",
        "stWalletTest/walletDefault.json",
        "stWalletTest/walletDefaultWithOutValue.json",
        "stWalletTest/walletExecuteOverDailyLimitMultiOwner.json",
        "stWalletTest/walletExecuteOverDailyLimitOnlyOneOwner.json",
        "stWalletTest/walletExecuteOverDailyLimitOnlyOneOwnerNew.json",
        "stWalletTest/walletExecuteUnderDailyLimit.json",
        "stWalletTest/walletKill.json",
        "stWalletTest/walletKillNotByOwner.json",
        "stWalletTest/walletKillToWallet.json",
        "stWalletTest/walletRemoveOwnerRemovePendingTransaction.json",
        "stZeroCallsRevert/ZeroValue_CALL_ToOneStorageKey_OOGRevert_Paris.json",
        "stZeroCallsRevert/ZeroValue_CALL_ToOneStorageKey_OOGRevert.json",
        "stZeroCallsRevert/ZeroValue_CALLCODE_ToOneStorageKey_OOGRevert_Paris.json",
        "stZeroCallsRevert/ZeroValue_CALLCODE_ToOneStorageKey_OOGRevert.json",
        "stZeroCallsRevert/ZeroValue_DELEGATECALL_ToOneStorageKey_OOGRevert_Paris.json",
        "stZeroCallsRevert/ZeroValue_DELEGATECALL_ToOneStorageKey_OOGRevert.json",
        "stZeroCallsRevert/ZeroValue_SUICIDE_ToOneStorageKey_OOGRevert_Paris.json",
        "stZeroCallsRevert/ZeroValue_SUICIDE_ToOneStorageKey_OOGRevert.json",
        "stZeroCallsTest/ZeroValue_CALL_ToEmpty.json",
        "stZeroCallsTest/ZeroValue_CALL_ToOneStorageKey_Paris.json",
        "stZeroCallsTest/ZeroValue_CALL_ToOneStorageKey.json",
        "stZeroCallsTest/ZeroValue_CALLCODE_ToOneStorageKey_Paris.json",
        "stZeroCallsTest/ZeroValue_CALLCODE_ToOneStorageKey.json",
        "stZeroCallsTest/ZeroValue_DELEGATECALL_ToOneStorageKey_Paris.json",
        "stZeroCallsTest/ZeroValue_DELEGATECALL_ToOneStorageKey.json",
        "stZeroCallsTest/ZeroValue_SUICIDE_ToEmpty_Paris.json",
        "stZeroCallsTest/ZeroValue_SUICIDE_ToEmpty.json",
        "stZeroCallsTest/ZeroValue_SUICIDE_ToNonZeroBalance.json",
        "stZeroCallsTest/ZeroValue_SUICIDE_ToOneStorageKey_Paris.json",
        "stZeroCallsTest/ZeroValue_SUICIDE_ToOneStorageKey.json",
        "stZeroCallsTest/ZeroValue_SUICIDE.json",
        "stZeroCallsTest/ZeroValue_TransactionCALL_ToEmpty.json",
        "stZeroCallsTest/ZeroValue_TransactionCALL_ToOneStorageKey_Paris.json",
        "stZeroCallsTest/ZeroValue_TransactionCALL_ToOneStorageKey.json",
        "stZeroCallsTest/ZeroValue_TransactionCALLwithData_ToEmpty.json",
        "stZeroCallsTest/ZeroValue_TransactionCALLwithData_ToOneStorageKey_Paris.json",
        "stZeroCallsTest/ZeroValue_TransactionCALLwithData_ToOneStorageKey.json",
        "stZeroKnowledge/ecmul_1-2_2_28000_128.json",
        "stZeroKnowledge/ecmul_1-2_2_28000_96.json",
        "stZeroKnowledge/ecmul_1-2_340282366920938463463374607431768211456_28000_128.json",
        "stZeroKnowledge/ecmul_1-2_340282366920938463463374607431768211456_28000_80.json",
        "stZeroKnowledge/ecmul_1-2_340282366920938463463374607431768211456_28000_96.json",
        "stZeroKnowledge/ecmul_1-2_5616_28000_128.json",
        "stZeroKnowledge/ecmul_1-2_5617_28000_128.json",
        "stZeroKnowledge/ecmul_1-2_5617_28000_96.json",
        "stZeroKnowledge/ecmul_1-2_616_28000_96.json",
        "stZeroKnowledge/ecmul_1-2_9_28000_128.json",
        "stZeroKnowledge/ecmul_1-2_9_28000_96.json",
        "stZeroKnowledge/ecmul_1-2_9935_28000_128.json",
        "stZeroKnowledge/ecmul_1-2_9935_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_0_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_0_28000_64.json",
        "stZeroKnowledge/ecmul_1-3_0_28000_80_Paris.json",
        "stZeroKnowledge/ecmul_1-3_0_28000_80.json",
        "stZeroKnowledge/ecmul_1-3_0_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_1_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_1_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_2_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_2_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_340282366920938463463374607431768211456_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_340282366920938463463374607431768211456_28000_80.json",
        "stZeroKnowledge/ecmul_1-3_340282366920938463463374607431768211456_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_5616_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_5616_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_5617_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_5617_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_9_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_9_28000_96.json",
        "stZeroKnowledge/ecmul_1-3_9935_28000_128.json",
        "stZeroKnowledge/ecmul_1-3_9935_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_0_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_0_28000_64.json",
        "stZeroKnowledge/ecmul_7827-6598_0_28000_80.json",
        "stZeroKnowledge/ecmul_7827-6598_0_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_1_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_1_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_1456_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_1456_28000_80.json",
        "stZeroKnowledge/ecmul_7827-6598_1456_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_2_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_2_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_5616_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_5616_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_5617_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_5617_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_9_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_9_28000_96.json",
        "stZeroKnowledge/ecmul_7827-6598_9935_28000_128.json",
        "stZeroKnowledge/ecmul_7827-6598_9935_28000_96.json",
        "stZeroKnowledge/ecpairing_bad_length_191.json",
        "stZeroKnowledge/ecpairing_bad_length_193.json",
        "stZeroKnowledge/ecpairing_inputs.json",
        "stZeroKnowledge/ecpairing_one_point_fail.json",
        "stZeroKnowledge/ecpairing_one_point_insufficient_gas.json",
        "stZeroKnowledge/ecpairing_one_point_not_in_subgroup.json",
        "stZeroKnowledge/ecpairing_one_point_with_g1_zero.json",
        "stZeroKnowledge/ecpairing_one_point_with_g2_zero_and_g1_invalid.json",
        "stZeroKnowledge/ecpairing_one_point_with_g2_zero.json",
        "stZeroKnowledge/ecpairing_perturb_g2_by_curve_order.json",
        "stZeroKnowledge/ecpairing_perturb_g2_by_field_modulus_again.json",
        "stZeroKnowledge/ecpairing_perturb_g2_by_field_modulus.json",
        "stZeroKnowledge/ecpairing_perturb_g2_by_one.json",
        "stZeroKnowledge/ecpairing_perturb_zeropoint_by_curve_order.json",
        "stZeroKnowledge/ecpairing_perturb_zeropoint_by_field_modulus.json",
        "stZeroKnowledge/ecpairing_perturb_zeropoint_by_one.json",
        "stZeroKnowledge/ecpairing_three_point_fail_1.json",
        "stZeroKnowledge/ecpairing_three_point_match_1.json",
        "stZeroKnowledge/ecpairing_two_point_fail_1.json",
        "stZeroKnowledge/ecpairing_two_point_fail_2.json",
        "stZeroKnowledge/ecpairing_two_point_match_1.json",
        "stZeroKnowledge/ecpairing_two_point_match_2.json",
        "stZeroKnowledge/ecpairing_two_point_match_3.json",
        "stZeroKnowledge/ecpairing_two_point_match_4.json",
        "stZeroKnowledge/ecpairing_two_point_match_5.json",
        "stZeroKnowledge/ecpairing_two_point_oog.json",
        "stZeroKnowledge/ecpairing_two_points_with_one_g2_zero.json",
        "stZeroKnowledge2/ecadd_0-0_0-0_21000_80.json",
        "stZeroKnowledge2/ecadd_0-0_0-0_25000_0.json",
        "stZeroKnowledge2/ecadd_0-0_0-0_25000_192.json",
        "stZeroKnowledge2/ecadd_0-0_0-0_25000_64.json",
        "stZeroKnowledge2/ecadd_0-0_0-0_25000_80.json",
        "stZeroKnowledge2/ecadd_0-0_1-2_25000_128.json",
        "stZeroKnowledge2/ecadd_0-0_1-2_25000_192.json",
        "stZeroKnowledge2/ecadd_0-0_1-3_25000_128.json",
        "stZeroKnowledge2/ecadd_0-3_1-2_25000_128.json",
        "stZeroKnowledge2/ecadd_1-2_0-0_25000_128.json",
        "stZeroKnowledge2/ecadd_1-2_0-0_25000_192.json",
        "stZeroKnowledge2/ecadd_1-2_0-0_25000_64.json",
        "stZeroKnowledge2/ecadd_1-2_1-2_25000_128.json",
        "stZeroKnowledge2/ecadd_1-2_1-2_25000_192.json",
        "stZeroKnowledge2/ecadd_1-3_0-0_25000_80_Paris.json",
        "stZeroKnowledge2/ecadd_1-3_0-0_25000_80.json",
        "stZeroKnowledge2/ecadd_1145-3932_1145-4651_25000_192.json",
        "stZeroKnowledge2/ecadd_1145-3932_2969-1336_25000_128.json",
        "stZeroKnowledge2/ecadd_6-9_19274124-124124_25000_128.json",
        "stZeroKnowledge2/ecmul_0-0_0_28000_0.json",
        "stZeroKnowledge2/ecmul_0-0_0_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_0_28000_40.json",
        "stZeroKnowledge2/ecmul_0-0_0_28000_64.json",
        "stZeroKnowledge2/ecmul_0-0_0_28000_80.json",
        "stZeroKnowledge2/ecmul_0-0_1_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_1_28000_96.json",
        "stZeroKnowledge2/ecmul_0-0_2_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_2_28000_96.json",
        "stZeroKnowledge2/ecmul_0-0_340282366920938463463374607431768211456_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_340282366920938463463374607431768211456_28000_80.json",
        "stZeroKnowledge2/ecmul_0-0_340282366920938463463374607431768211456_28000_96.json",
        "stZeroKnowledge2/ecmul_0-0_5616_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_5616_28000_96.json",
        "stZeroKnowledge2/ecmul_0-0_5617_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_5617_28000_96.json",
        "stZeroKnowledge2/ecmul_0-0_9_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_9_28000_96.json",
        "stZeroKnowledge2/ecmul_0-0_9935_28000_128.json",
        "stZeroKnowledge2/ecmul_0-0_9935_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_0_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_0_28000_64.json",
        "stZeroKnowledge2/ecmul_0-3_0_28000_80.json",
        "stZeroKnowledge2/ecmul_0-3_0_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_1_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_1_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_2_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_2_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_340282366920938463463374607431768211456_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_340282366920938463463374607431768211456_28000_80.json",
        "stZeroKnowledge2/ecmul_0-3_340282366920938463463374607431768211456_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_5616_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_5616_28000_96_Paris.json",
        "stZeroKnowledge2/ecmul_0-3_5616_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_5617_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_5617_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_9_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_9_28000_96.json",
        "stZeroKnowledge2/ecmul_0-3_9935_28000_128.json",
        "stZeroKnowledge2/ecmul_0-3_9935_28000_96.json",
        "stZeroKnowledge2/ecmul_1-2_0_28000_128.json",
        "stZeroKnowledge2/ecmul_1-2_0_28000_64.json",
        "stZeroKnowledge2/ecmul_1-2_0_28000_80.json",
        "stZeroKnowledge2/ecmul_1-2_0_28000_96.json",
        "stZeroKnowledge2/ecmul_1-2_1_28000_128.json",
        "stZeroKnowledge2/ecmul_1-2_1_28000_96.json",
        "VMTests/vmArithmeticTest/fib.json",
        "VMTests/vmIOandFlowOperations/gas.json",
        "VMTests/vmIOandFlowOperations/jump.json",
        "VMTests/vmIOandFlowOperations/jumpi.json",
        "VMTests/vmIOandFlowOperations/loopsConditionals.json",
        "VMTests/vmIOandFlowOperations/mload.json",
        "VMTests/vmIOandFlowOperations/mstore.json",
        "VMTests/vmIOandFlowOperations/mstore8.json",
        "VMTests/vmIOandFlowOperations/pc.json",
        "VMTests/vmIOandFlowOperations/return.json",
        "VMTests/vmIOandFlowOperations/sstore_sload.json",
        "VMTests/vmLogTest/log0.json",
        "VMTests/vmLogTest/log1.json",
        "VMTests/vmLogTest/log2.json",
        "VMTests/vmLogTest/log3.json",
        "VMTests/vmLogTest/log4.json",
        "VMTests/vmTests/suicide.json",
    ].into_iter().any(|test_name| path.ends_with(test_name))
}

#[test]
fn ethereum_tests() {
    WalkDir::new("tests/ethereum/tests/GeneralStateTests")
        .into_iter()
        .filter_map(Result::ok)
        .map(DirEntry::into_path)
        .filter(|path| path.extension() == Some("json".as_ref()))
        .filter(|path| !should_skip_test(path))
        .collect::<Vec<_>>()
        .par_iter() // TODO: Further improve test speed
        .for_each(|path| {
            println!("Running: {path:?}");
            let raw_content = fs::read_to_string(path)
                .unwrap_or_else(|_| panic!("Cannot read suite: {:?}", path));
            let TestSuite(suite) = serde_json::from_str(&raw_content)
                .unwrap_or_else(|_| panic!("Cannot parse suite: {:?}", path));
            for (_, unit) in suite {
                run_test_unit(unit)
            }
        });
}
