name: Rust Format Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run fmt
        run: cargo fmt --all --check
